### ISSUE TITLE
Replay Tests creating unwanted files

### ISSUE THREAD

**Issue by iaronaraujo** [Terasology/TestReplayModule#4]
Right now, the execution of a Replay Test creates some unwanted files (config and screenshots). Those files are already in the gitignore, but it would be ideal if they were never created during the execution of a replay test.

**Comment by llvieira** [comment]
I was trying to figure out the reason why those screenshots are saved, then I found the following:
1. Those screenshots are created/saved in [WorldAtlasImpl#createAtlasMipmaps()](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/world/block/tiles/WorldAtlasImpl.java#L275) as soon as the game starts running.
2. After saving it, they are used to create texture data, which are the terrains.
3. Then, if somehow you don't save those screenshots, the game cannot continue its execution.
4. The `HeadlessEnvironment` uses `NullWorldAtlas` which is the dummy implementation of world atlas in which it does not save any file.
5. However, I didn't see any way of using `HeadlessEnvironment` instead of `ReplayTestingEnvironment`. Moreover, in a headed environment all the files will definitively be there.

Therefore, in my point of view preventing tests from saving _unwanted_ files does seems unworkable, since we can't even execute the engine properly without them.

**Comment by iaronaraujo** [comment]
That makes sense. When I created this issue I already thought that it wouldn't be possible to make replay tests not generate unwanted files, but now that you looked into it, we can be sure of that. I am going to close this issue now. Thanks for your research!
